import { type NextPage } from "next";
import { Header } from "../components/header";
import { ItemList } from "../components/itemList";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
	return (
		<>
			<header>
				<title>Marketplace</title>
				<meta name = 'description' content = 'Generated by create-t3-app'/>
				<link rel = 'icon' href = '/favicon.ico'/>
			</header>

			<main className="min-h-screen bg-gradient-to-br from-indigo-500 via-purple-500 to-pink-500 font-semibold">
				<Header/>
				<ItemList/>
			</main>
		</>
	);
};

export default Home;
